ProjectDB/Models/Students.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

using Microsoft.AspNetCore.Mvc;
namespace ProjectDB.Models
{
    public class Students
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int StudentID { get; set; }

        [Required(ErrorMessage = "The name field is required")]
        [StringLength(20, ErrorMessage = "Max chars are 20")]
        [Display(Name = "Full Name")]
        public string Student_Name { get; set;}

        [Required]
        [RegularExpression(@"[a-z A-Z 0-9 _-]+@[a-z A-Z]+.[a-z  A-Z]{2,4}", ErrorMessage = "Invalid email format")]
        public string Student_Email { get; set;}

        [DataType(DataType.Date)]
        public DateTime Student_BD {  get; set;} 

        [ForeignKey("departments")]
        public int Dept_ID { get; set; }
        public Departments departments { get; set; }
    }
}

ProjectDB/Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using ProjectDB.Models;
using ProjectDB.NewFolder;
using ProjectDB.Repository;

namespace ProjectDB.Controllers
{
    public class ExamController : Controller
    {
        ProjectDBContext db = new ProjectDBContext();

        public IActionResult GenerateExam(int id, int SI)
        {

            var questionsWithChoices = db.Questions
                .Where(q => q.CrsID == id && q.Question_Type == "MCQ")
                .Join(db.Choices, q => q.QuestionID, c => c.Q_ID, (q, c) => new { Question = q, Choice = c })
                .OrderBy(x => Guid.NewGuid()) 
                .Take(5) 
                .ToList();
            var questionsList = questionsWithChoices.Select(x => x.Question).ToList();
            //______________________

            List<Questions> tfQuestions = db.Questions.Where(q => q.CrsID == id && q.Question_Type == "True/False").ToList();

            // Shuffle the T/F questions
            tfQuestions = tfQuestions.OrderBy(q => Guid.NewGuid()).Take(5).ToList();

            // Combine MCQ and T/F questions
            List<Questions> selectedQuestions = questionsList.Concat(tfQuestions).ToList();

            // Separate the questions and choices into two lists   
            var choicesList = questionsWithChoices.Select(x => x.Choice).ToList();
            ViewBag.ListChoices= choicesList;
            ViewBag.StdId = SI;

            if (questionsList.Count < 5)
            {
                return View("Error");
            }
 
            return View(selectedQuestions);
        }

        [HttpPost]
        public IActionResult ProcessExam(List<int> questionIds, List<string> studentResponses, int SI,int id/*, string EI*/)
        {
            int grade = 0;

           
            List<string> RightAnswer = new List<string>();

            for (var i = 0; i < questionIds.Count(); i++)
            {
                var answer = db.Questions
                       .Where(q => q.QuestionID == questionIds[i])
                       .Select(a => a.Question_Answer)
                       .FirstOrDefault();
                if(answer!=null)
                {
                    RightAnswer.Add(answer);
                }
            }
         

            var crsWorkGrade = int.Parse(db.Course
           .Where(c => c.CourseID == id)
           .Join(db.Student_Courses, c => c.CourseID, s => s.CourseID, (c, s) => new { Courses = c, Student_Courses = s })
           .Select(c => c.Courses.CourseWork).FirstOrDefault()!);

            int TotalMarks = 100 - crsWorkGrade;

            for (int i =0;i<studentResponses.Count();i++)
            {
                if (studentResponses[i] == RightAnswer[i])
                {
                    /*int cWork*/
                    grade += TotalMarks/10;
                }
            }

            Exams Exam = new Exams {Total_Marks = TotalMarks, CrsID = id };
            db.Exams.Add(Exam);
            db.SaveChanges();

            // Retrieve the generated PK value
            int generatedPKValue = Exam.ExamID;

      
            var studentCourse = db.Student_Courses
                .FirstOrDefault(c => c.CourseID == id && c.StudentID == SI);

            if (studentCourse != null)
            {
                studentCourse.Student_Grade = grade;
                db.SaveChanges(); // Commit changes to the database
            }
            ViewBag.totalMarks = TotalMarks;
            ViewBag.StdId = SI;

            for (var i = 0; i < questionIds.Count(); i++)
            {
                ExamQuestionResponse stdRes = new ExamQuestionResponse()
                { ExamID = generatedPKValue, StudentID = SI, QuestionID = questionIds[i], StudentResponse = studentResponses[i] };

       
                db.examQuestionResponses.Add(stdRes);
                db.SaveChanges();
            }

            return View(grade);

        }


    }
}

ProjectDB/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectDB.LoginViewModel;
using ProjectDB.Models;
using ProjectDB.NewFolder;
using ProjectDB.Repository;
using ProjectDB.ViewModel;
using ProjectDB.ViewModels;

namespace ProjectDB.Controllers
{
    public class StudentController : Controller
    {
        IStudentRepo studentRepo;
        ProjectDBContext db = new ProjectDBContext();
        public StudentController(IStudentRepo _studentRepo)
        {
            studentRepo = _studentRepo;
        }


        public IActionResult Index()
        {
            return View();
        }

       
        public IActionResult ViewCoursesStudent(int id)
        {
            
            if (id == 0)
            {
                return BadRequest();
            }
            var stdmodel = db.Student.Include(m => m.departments).FirstOrDefault(a => a.StudentID == id);
            var stdcrsIdmodel = db.Student_Courses
                                .Include(sc => sc.Courses)
                                .Where(sc => sc.StudentID == id)
                                .Select(sc => sc.Courses.CourseID)
                                .ToList();
            if (stdmodel == null)
            {
                return NotFound();
            }

            var stdcrsmodel = db.Student_Courses
                                .Include(sc => sc.Courses)
                                .Where(sc => sc.StudentID ==id)
                                .Select(sc => sc.Courses.Course_Name)
                                .ToList();
 
            if (stdcrsmodel == null)
            {
                return NotFound();
            }


            // Create a ViewModel for each course
            var model = new StudentDepartmentCourseViewModel
            {
                StudentId = stdmodel.StudentID,
                StudentName = stdmodel.Student_Name,
                DeptName = stdmodel.departments!.DeptName, // Use null-conditional operator
                DeptId = stdmodel.Dept_ID,
                courseName = stdcrsmodel, // Directly access course name
                crsId = stdcrsIdmodel,
            };
            return View(model);
        }
        public IActionResult ShowGrade(string courseIds, int SI)
        {
            // Split the comma-separated string of course IDs into an array
            var courseIdArray = courseIds.Split(',').Select(int.Parse).ToList();
            List<int> crswrklist = new List<int>();

            var model = db.Student_Courses.Include(sc => sc.Courses).Include(s => s.Students)
                             .Where(sc => sc.StudentID == SI).ToList();

            foreach (var crs in courseIdArray)
            {
                var crsWorkGrade = int.Parse(db.Course
                 .Where(c => c.CourseID ==crs )
                 .Join(db.Student_Courses, c => c.CourseID, s => s.CourseID, (c, s) => new { Courses = c, Student_Courses = s })
                  .Select(c => c.Courses.CourseWork).FirstOrDefault()!);
                   crswrklist.Add(crsWorkGrade);
            }
            ViewBag.courseWork=crswrklist;
           
            return View(model);
        }

    }
}

ProjectDB/Views/Student/ShowGrade.cshtml
@model List<Student_Courses>;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ShowGrade</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="text-center">@Model[1].Students.Student_Name</h1>
        @for (int i = 0; i < Model.Count(); i++)
        {
            <div class="card mt-3">
                <div class="card-body">
                    <h2>@Model[i].Courses.Course_Name</h2>
                    <p class="mb-1">Grade: @Model[i].Student_Grade</p>
                    @if (ViewBag.courseWork != null && ViewBag.courseWork.Count > i)
                    {
                        <p class="mb-1"> CourseWork: @(ViewBag.courseWork[i]) / @(ViewBag.courseWork[i])</p>
                        <p class="mb-1">Total Grade: @(ViewBag.courseWork[i] + Model[i].Student_Grade) / 100</p>
                    }
                </div>
            </div>
        }
    </div>

    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

ProjectDB/Views/Student/ViewCoursesStudent.cshtml
@model StudentDepartmentCourseViewModel;
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ViewCoursesStudent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            color: #343a40;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            background-color: #fff;
        }

        .card-header {
            background-color: #901b20;
            color: #fff;
            border-radius: 10px 10px 0 0;
        }

        .card-body {
            padding: 20px;
        }

        .info-label {
            font-weight: bold;
        }

        .info-value {
            color: #6c757d;
        }

        .btn {
            background-color: #901b20;
            border-color: #901b20;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 class="text-center mb-0">Student Information</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <p class="info-label">Name:</p>
                        <p class="info-value">@Model.StudentName</p>
                    </div>
                    <div class="col-md-6">
                        <p class="info-label">Student ID:</p>
                        <p class="info-value">@Model.StudentId</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p class="info-label">Track:</p>
                        <p class="info-value">@Model.DeptName</p>
                    </div>
  
                </div>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-header">
                <h3 class="text-center mb-0">Course Listings</h3>
            </div>
            <div class="card-body">
                @if (Model.courseName.Count() == 0)
                {
                    <p class="text-center">No Existing courses</p>
                }
                else
                {
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            @for (int i = 0; i < Model.courseName.Count(); i++)
                            {
                                <tr>
                                    <td>@Model.courseName[i]</td>
                                    <td>
                                         <a class="btn" href="@Url.Action("GenerateExam", "Exam", new { id = Model.crsId[i], SI = Model.StudentId })">Exam</a> 
                                    </td>
                                </tr>
                            }

                        </table>
                        <a class="btn" href="@Url.Action("ShowGrade", "Student", new { courseIds = string.Join(",", Model.crsId), SI = Model.StudentId })">Grades</a>
                        <a class="btn" asp-controller="Home" asp-action="Index">Logout</a>

                    </div>
                }
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>